name: Build Termux Package Cache (aarch64 only)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: "Clone Repository"
      run: |
        git clone https://github.com/moio9/termux-lib-builder

    - name: "Environment Preparation"
      run: |
        sudo apt update
        sudo apt install -y python3 python3-pip cmake wget git p7zip build-essential pkg-config xmlto fop xsltproc llvm autoconf libxml-parser-perl bison flex glslang-tools
        pip3 install mako meson ninja docutils StrEnum
        sudo ln -sf ~/.local/bin/meson /usr/bin/meson

    - name: "Download Previous Package Cache (Optional)"
      run: |
        cd termux-lib-builder
        curl -LO# https://github.com/KreitinnSoftware/MiceWine-RootFS-Generator/releases/download/$(curl -s https://api.github.com/repos/KreitinnSoftware/MiceWine-RootFS-Generator/releases | grep tag_name -m 1 | cut -d ":" -f 2 | sed "s/\"//g" | sed "s/,//g" | sed "s/ //g")/MiceWine-Packages.zip || true
        unzip -o MiceWine-Packages.zip -d built-pkgs || true

    - name: "Build All Packages (aarch64)"
      run: |
        cd termux-lib-builder
        ./build-all.sh aarch64 --ci

    - name: "Save Package Cache as .tar"
      run: |
        cd termux-lib-builder
        tar -cf /home/runner/Termux-Packages.tar -C built-pkgs .

    - name: "Get Short SHA"
      run: |
        cd termux-lib-builder
        echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
        
    - name: "Upload Package Cache to Release"
      uses: softprops/action-gh-release@v2
      with:
        name: "Termux Packages Cache (${{ env.SHORT_SHA }})"
        tag_name: ${{ env.SHORT_SHA }}
        prerelease: true
        files: |
          /home/runner/Termux-Packages.tar

